"""Initial migration peliculas

Revision ID: c07771dac949
Revises: 
Create Date: 2026-03-07 18:02:14.852579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07771dac949'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas_etl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('registros_extraidos', sa.Integer(), nullable=True),
    sa.Column('registros_guardados', sa.Integer(), nullable=True),
    sa.Column('registros_fallidos', sa.Integer(), nullable=True),
    sa.Column('tiempo_ejecucion_segundos', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_etl_fecha_ejecucion'), 'metricas_etl', ['fecha_ejecucion'], unique=False)
    op.create_index(op.f('ix_metricas_etl_id'), 'metricas_etl', ['id'], unique=False)
    op.create_table('peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peliculas_id'), 'peliculas', ['id'], unique=False)
    op.create_index(op.f('ix_peliculas_titulo'), 'peliculas', ['titulo'], unique=True)
    op.create_table('registro_peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pelicula_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('actores', sa.String(length=500), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('recaudacion', sa.Float(), nullable=True),
    sa.Column('idioma', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pelicula_id'], ['peliculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pelicula_fecha', 'registro_peliculas', ['pelicula_id', 'fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_registro_peliculas_fecha_extraccion'), 'registro_peliculas', ['fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_registro_peliculas_id'), 'registro_peliculas', ['id'], unique=False)
    op.create_index(op.f('ix_registro_peliculas_pelicula_id'), 'registro_peliculas', ['pelicula_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_peliculas_pelicula_id'), table_name='registro_peliculas')
    op.drop_index(op.f('ix_registro_peliculas_id'), table_name='registro_peliculas')
    op.drop_index(op.f('ix_registro_peliculas_fecha_extraccion'), table_name='registro_peliculas')
    op.drop_index('idx_pelicula_fecha', table_name='registro_peliculas')
    op.drop_table('registro_peliculas')
    op.drop_index(op.f('ix_peliculas_titulo'), table_name='peliculas')
    op.drop_index(op.f('ix_peliculas_id'), table_name='peliculas')
    op.drop_table('peliculas')
    op.drop_index(op.f('ix_metricas_etl_id'), table_name='metricas_etl')
    op.drop_index(op.f('ix_metricas_etl_fecha_ejecucion'), table_name='metricas_etl')
    op.drop_table('metricas_etl')
    # ### end Alembic commands ###
