"""Initial migration

Revision ID: 4e1c9e1afd49
Revises: 
Create Date: 2026-03-07 17:16:24.090782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1c9e1afd49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciudades_id'), 'ciudades', ['id'], unique=False)
    op.create_index(op.f('ix_ciudades_nombre'), 'ciudades', ['nombre'], unique=True)
    op.create_table('metricas_etl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('registros_extraidos', sa.Integer(), nullable=True),
    sa.Column('registros_guardados', sa.Integer(), nullable=True),
    sa.Column('registros_fallidos', sa.Integer(), nullable=True),
    sa.Column('tiempo_ejecucion_segundos', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_etl_fecha_ejecucion'), 'metricas_etl', ['fecha_ejecucion'], unique=False)
    op.create_index(op.f('ix_metricas_etl_id'), 'metricas_etl', ['id'], unique=False)
    op.create_table('registros_clima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('sensacion_termica', sa.Float(), nullable=True),
    sa.Column('humedad', sa.Float(), nullable=True),
    sa.Column('velocidad_viento', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('codigo_tiempo', sa.Integer(), nullable=True),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ciudad_fecha', 'registros_clima', ['ciudad_id', 'fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_registros_clima_ciudad_id'), 'registros_clima', ['ciudad_id'], unique=False)
    op.create_index(op.f('ix_registros_clima_fecha_extraccion'), 'registros_clima', ['fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_registros_clima_id'), 'registros_clima', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_clima_id'), table_name='registros_clima')
    op.drop_index(op.f('ix_registros_clima_fecha_extraccion'), table_name='registros_clima')
    op.drop_index(op.f('ix_registros_clima_ciudad_id'), table_name='registros_clima')
    op.drop_index('idx_ciudad_fecha', table_name='registros_clima')
    op.drop_table('registros_clima')
    op.drop_index(op.f('ix_metricas_etl_id'), table_name='metricas_etl')
    op.drop_index(op.f('ix_metricas_etl_fecha_ejecucion'), table_name='metricas_etl')
    op.drop_table('metricas_etl')
    op.drop_index(op.f('ix_ciudades_nombre'), table_name='ciudades')
    op.drop_index(op.f('ix_ciudades_id'), table_name='ciudades')
    op.drop_table('ciudades')
    # ### end Alembic commands ###
